export const formQuestion = [
  {
    id: 1,
    question: "Please Provide your name",
    placeholder: "Name Please",
    button: "Next",
    type: "input",
    name: "name",
    message: null,
  },
  {
    id: 2,
    question: "We want your email.",
    placeholder: "Gather Emails? Prawns!",
    button: "peawns!",
    message: " will exchange this info with spammers for Prawns!",
    type: "input",
    name: "email",
  },
  {
    id: 3,
    question: "Write your Meowssage",
    placeholder: "If we could read we might just read this between naps and meal times",
    button: "peawns!",
    type: "text",
    name: "text",
    message: null,
  },
  {
    id: 4,
    question: "So long and thanks for all the fish.",
    placeholder: null,
    button: "thank you",
    type: "submit",
    name: null,
    message: null,
  },
];
